config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'course'=>'home#course',as: :course
  
  #############ユーザー用画面##############
  get 'profile'=>'users#index',as: :profiles
  post 'profile'=>'users#create'
  patch 'profile'=>'users#update'
  get 'sign_out'=>'users#sign_out',as: :sign_out
  get 'profile/edit'=>'users#edit',as: :profile_edit

  #############api##########################
  get '/api/subscriptions'=>'api#subscriptions',as: :subscriptions
  get '/api/non_subscriptions'=>'api#non_subscriptions',as: :non_subscriptions
  
  ############支払い関連###############
  get '/payment'=>'users#payment',as: :payment
  #支払い成功
  #get '/payment/:course_id/succeeded/:session'=>'payments#payment_succeeded',as: :payment_succeeded
  get '/payment/subscription/succeeded/:session'=>'payments#payment_succeeded',as: :payment_succeeded
  #支払い失敗
  get '/payment/failed'=>'payments#payment_failed',as: :payment_failed
  #チェックアウトセッション
  post '/create_checkout_session'=>'payments#create_checkout_session',as: :checkout
  get 'tickets'=>'payments#get_tickets_from_price_id'
  post '/payment/delete/subscriptions'=>'payments#cancel_subscription'
  #支払いキャンセル
  post '/refund'=>'payments#refund',as: :refund
  post '/subscription/paied'=>'payments#subscription_paied',as: :subscription_paied
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_stripe_api_key
  
  def index
    LineAct.profile_action(@_request,self,LineUser,AccessLog)
    #current_userが存在して、かつcustomerが入っていない場合
    if !current_user.nil? && current_user.customer.nil?
      #customerを生成して保存する
      customer = Stripe::Customer.create({description: current_user.id})
      current_user.update(:customer=>customer[:id])
    end
    
    #顧客情報が入っていなければ
    if !current_user.nil? && !current_user.customer.nil?
      customer = Stripe::Customer.retrieve(current_user.customer)
      if customer[:email].nil?
        redirect_to profile_path and return
      end
    end
    
  end
  
  def payment
    #過去の支払い履歴
    @payments = Stripe::Charge.list({customer: current_user.customer}).data
  end
  
  def create
    current_user.build_profile(profile_params).save
    redirect_to profile_path
  end
  
  def edit
    
  end
  
  def update
    current_user.profile.update(profile_params)
    redirect_to profile_path
  end
  
  def sign_out
    LineAct.user_sign_out(@_request)
    current_user=nil
    redirect_to root_path
  end
  
  private
  #stripeのapi_keyを設定する
  def set_stripe_api_key
     Stripe.api_key = ENV['STRIPE_API_KEY']
  end
  
  def profile_params
    params.require(:profile).permit(:email,:name,:cname,:pref_id,:tel,:year,:month)
  end

end

app/helpers/users_helper.rb
module UsersHelper
    def current_user
        if @current_user.nil?
            @current_user = LineUser.find_by(:line_id=>session[:line_act_sub])
        else
            @current_user 
        end
    end
    
    def is_logined?
        current_user.present?
    end
    
    def is_admin?
       current_user.present? && current_user.admin==true 
    end
    
    def redirect_if_not_admin
       if is_admin? == false then redirect_to root_path end 
    end
    
    def redirect_if_not_logined
       if is_logined? == false then redirect_to root_path end 
    end
    
    def authorize
       @current_user = current_user 
    end
    
    def redirect_back_if_not_admin
       redirect_to root_path and return unless is_admin?
    end
    

end

app/views/users/_edit_form.html.erb
<% current_user.profile.nil? ? m=Profile.new : m=current_user.profile %>

<%= form_with model: m,class:'form-group user_edit_form' do |p| %>
    <%= p.label :email, 'EMAIL' ,class: 'form-label' %>
    <%= p.text_field :email ,class: 'form-control' %>
    <%= p.label :name, 'お名前' ,class: 'form-label' %>
    <%= p.text_field :name, class: 'form-control' %>
    <%= p.label :cname, 'お子様の名前',class: 'form-label' %>
    <%= p.text_field :cname, class: 'form-control' %>
    <%= p.label :pref, '都道府県',class: 'form-label' %>
    <%= p.collection_select :pref_id,Pref.all,:id,:name,{include_blank: true}, {class: 'form-control'} %>
    <%= p.label :tel, '電話番号',class: 'form-label' %>
    <%= p.text_field :tel, class: 'form-control' %>
    <%= p.label :year, 'お子様の生まれ年',class: 'form-label' %>
    <%= p.select :year, 2000..Time.now.year.to_i,{include_blank: true}, class: 'form-control' %>
    <%= p.label :month, 'お子様の生まれ月',class: 'form-label' %>
    <%= p.select :month, 1..12,{include_blank: true},class: 'form-control' %>
    <%= p.submit '登録',class: 'btn btn-primary w-100 add_button' %>
<% end %>

<script>
    window.onload = function(){
        document.getElementsByClassName('add_button')[0].setAttribute('disabled','disabled')
        let inputs = document.getElementsByTagName('input');
        let selects = document.getElementsByTagName('select');
        Object.keys(inputs).forEach(function(key){
            inputs[key].addEventListener('change',set_add_button,false);
        })
        Object.keys(selects).forEach(function(key){
            selects[key].addEventListener('change',set_add_button,false);
        })
        
        function set_add_button(){
            if(not_blank()===true){
                document.getElementsByClassName('add_button')[0].removeAttribute('disabled')
            }else{
                document.getElementsByClassName('add_button')[0].setAttribute('disabled','disabled')
            }
        }
        
        function not_blank(){
            let flag = true;
            Object.keys(inputs).forEach(function(key){
                if(inputs[key].value ===''){flag=false}
            })
            Object.keys(selects).forEach(function(key){
                if(selects[key].value===''){flag=false}
            })
            return flag;
        }
    }
</script>

app/views/users/edit.html.erb
<h2>会員情報編集</h2>

<%= render partial: 'edit_form' %>

app/views/users/index.html.erb
<h2>会員情報</h2>

<section>
    <dl class='profile'>
        <dt>LINEアカウント</dt>
        <dd><span class='profile_img' style='background-image:url(<%= current_user.picture %>)'></span><span><%= current_user.display_name %></span></dd>
        <dt>EMAIL</dt>
        <dd><%= current_user.profile.email %></dd>
        <dt>お名前</dt>
        <dd><%= current_user.profile.name %></dd>
        <dt>お子様のお名前</dt>
        <dd><%= current_user.profile.cname %></dd>
        <dt>お住まいの都道府県</dt>
        <dd><%= current_user.profile.pref.name %></dd>
        <dt>電話番号</dt>
        <dd><%= current_user.profile.tel %></dd>
        <dt>お子様の生まれ月</dt>
        <dd><%= current_user.profile.year %>年<%= current_user.profile.month %>月</dd>
        <dt>学年</dt>
        <dd><%= current_user.profile.gakunen %></dd>
    </dl>
</section>

app/views/users/payment.html.erb
<h2>コース選択</h2>
<section id='course' class='course' payment='true' api_key='<%= ENV['STRIPE_API_PUBLIC_KEY'] %>' contract_course_id='<%= current_user.course_id %>'></section>

<h2>お支払い履歴</h2>
<section>
    <% if current_user.payment_logs.any? %>
    <table class='table table-striped text-center'>
        <thead>
            <tr>
                <th>決済日時</th>
                <th>金額</th>
                <th>領収書</th>
                <th>返金</th>
            </tr>
        </thead>
        <tbody>
            <% @payments.each do |p| %>
            <tr>
                <td><%= Time.at(p.created.to_i).strftime('%Y年%m月%d日 %H:%M:%S') %></td>
                <td>&yen;<%= p.amount.to_s(:delimited) %></td>
                <td>
                    <%= link_to p.receipt_url, target: :_blank do %>
                    <button class='btn btn-info'>領収書</button>
                    <% end %>
                </td>
                <td>
                    <!-- クーリングオフ制約 -->
                    <% if (Time.now.to_i - p.created.to_i)/(3600*24) < 8 then %>
                        <% pi = PaymentLog.find_by(:payment_intent=>p.payment_intent) %>
                        <% if able_to_refund?(p) %>
                            <%= form_with url: refund_path do |f| %>
                                <%= f.hidden_field :payment_log_id, value: pi.id %>
                                <%= f.submit '返金',class: 'btn btn-warning', data: { confirm: "本当に返金しますか？"} %>
                            <% end %>
                        <% end %>
                    <% end %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <% end %>
</section>