config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'course'=>'home#course',as: :course
  
  #############ユーザー用画面##############
  get 'profile'=>'users#index',as: :profiles
  post 'profile'=>'users#create'
  patch 'profile'=>'users#update'
  get 'sign_out'=>'users#sign_out',as: :sign_out
  get 'profile/edit'=>'users#edit',as: :profile_edit

  #############api##########################
  get '/api/subscriptions'=>'api#subscriptions',as: :subscriptions
  get '/api/non_subscriptions'=>'api#non_subscriptions',as: :non_subscriptions
  
  ############支払い関連###############
  get '/payment'=>'users#payment',as: :payment
  #支払い成功
  #get '/payment/:course_id/succeeded/:session'=>'payments#payment_succeeded',as: :payment_succeeded
  get '/payment/subscription/succeeded/:session'=>'payments#payment_succeeded',as: :payment_succeeded
  #支払い失敗
  get '/payment/failed'=>'payments#payment_failed',as: :payment_failed
  #チェックアウトセッション
  post '/create_checkout_session'=>'payments#create_checkout_session',as: :checkout
  get 'tickets'=>'payments#get_tickets_from_price_id'
  post '/payment/delete/subscriptions'=>'payments#cancel_subscription'
  #支払いキャンセル
  post '/refund'=>'payments#refund',as: :refund
  post '/subscription/paied'=>'payments#subscription_paied',as: :subscription_paied
end

app/views/layouts/_carousel.html.erb
<div class='carousel' pics='["top_before.jpg","top_after.jpg"]' messages='["解説を読んでも\nわからなければ","解説動画で\nスパッと解決"]' ></div>

app/views/layouts/_header.html.erb
<div class='wave_back'></div>
<%= link_to root_path,class: 'logo',data: {"turbolinks" => false} do %>
    <%= image_tag 'logo.png' %>
<% end %>
<%= link_to profiles_path,class: 'profile_link',data: {"turbolinks" => false}  do %>
    <%= image_tag 'btn_login_base.png' %>
<% end %>

<!--メニュー-->
<nav>
    <%= link_to 'わかる！解説動画',root_path, data:{"turbolinks"=>false} %>
    <%= link_to 'わかる！解説動画',root_path, data:{"turbolinks"=>false} %>
    <%= link_to '月額コース紹介',course_path, data:{"turbolinks"=>false} %>
    <%= link_to 'わかる！解説動画',root_path, data:{"turbolinks"=>false} %>
</nav>

<!--ログイン後のメニュー-->
<% if is_logined? %>
<nav>
    <%= link_to '会員トップ',profiles_path,data:{"turbolinks"=>false} %>
    <%= link_to '会員情報編集',profile_edit_path,data:{"turbolinks"=>false} %>
    <%= link_to 'お支払い',payment_path,data:{"turbolinks"=>false} %>
    <%= link_to 'サインアウト',sign_out_path,data:{"turbolinks"=>false} %>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpresstutorV8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= render partial: 'layouts/carousel' %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>